### ISSUE TITLE
Question on CnR run

### ISSUE THREAD

**Issue by EllieDuan** [RenneLab/CnR-flow#2]
Hello,

Thanks for making this pipeline, I'm excited to give it a try. 
After set up the genome fa and fastq file paths, I tried `prep_fasta `and `list_refs` ,  they all worked well, but both `dry_run` and `run` seem not to work. Here is it prints:

`N E X T F L O W  ~  version 20.10.0`
`Launching RenneLab/CnR-flow [jolly_elion] - revision: fb398b9301 [master]`
`Utilizing Run Mode: dry_run`
`-- Preparing Workflow Environment --`
`74 Input Files Detected.`
`-- Executing Workflow --`

`N E X T F L O W  ~  version 20.10.0`
`Launching RenneLab/CnR-flow [special_ride] - revision: fb398b9301 [master]`
`Utilizing Run Mode: run`
`-- Preparing Workflow Environment --`
`74 Input Files Detected.`
`-- Executing Workflow --`

Could you please provide some guidance on where to look for the problem? Thank you!

Best,
Ellie

**Comment by EllieDuan** [comment]
Should I use unzip fastq file as the input? Thanks!

**Comment by EllieDuan** [comment]
It is working now! I put it into a bash and submit as a Slurm job.  I also uncommented the `executor = 'slurm' ` in the `process {}` section. 
Thanks, sorry about previous posts! It is running well now!

**Comment by dstrib** [comment]
Great! Glad it is working! Did you start by using the "--validate-all" mode? If not, then you might have been seeing a delay as the conda environments were downloaded and initialized (if you are using conda).

**Comment by EllieDuan** [comment]
Thank you!

I have some more questions.
1. If my samples do not use spike-in controls, should I turn off the parameter in`Aln_Spike`.

2. Can we run without IgG? I saw the `ctrl_fastqs` is not labeled as required. We only had IgG samples in our pilot experiments and I'm wondering if it can still be used for samples that generated in a different batch. 

3. I found one sample failed in the bowtie2 alignment (No Alignments Found). This file was made in an early batch and only used 25bp as sequencing length, but fastq file after trimming become 19bp (from S1_C_FastQC_post). I'm not sure if this is the reason it fails and If I can change/loosen up the trimming parameter or in bowtie2.  I have aligned this file using bowtie2 directly, it is working.  

My other files are working well, one has 38bp and another has 150bp. 

`4387788 reads; of these:
  4387788 (100.00%) were paired; of these:
    4387788 (100.00%) aligned concordantly 0 times
    0 (0.00%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
0.00% overall alignment rate
set +v +H +o history
Alignments: 0
No Alignments Found. Please check alignment paramaters and reference setup.`


Thanks a lot for your help.

**Comment by dstrib** [comment]
1. Meers et al. suggest in a recent publication that E. Coli that remains as a remnant of reagent preparation can be used as a spike-in control, and this is the default setting for the pipeline. ( https://elifesciences.org/articles/46314 ) However you will want to make sure that E. coli is present in your samples in sufficient quantity for efficient normalization (this is discussed on a few occasions in the online protocol for CUT&RUN: https://www.protocols.io/view/cut-amp-run-targeted-in-situ-genome-wide-profiling-zcpf2vn/comments?q=coli ). If you decide not to use it, you can set "do_norm_spike = false" in your config file and this will disable spike-in normalization. 
( For details: https://cnr-flow.readthedocs.io/en/latest/source/workflow.html#aln-spike )

2. Control samples are optional, so you are free not to provide them. Samples specified as controls (like IgG) are processed in parallel for the entire run until the peak calling step at the end. Then control sample(s), if present, are passed to SEACR or MACS2 along with each respective treatment as a baseline for peak calling. Both MACS2 and SEACR can also call peaks without control samples, but differ in how peaks are called somewhat with/without them. 
( For details: https://cnr-flow.readthedocs.io/en/latest/source/workflow.html#peak-calling-steps )

3. Yes I suspect the short sequence length would be an issue there. If you have Bowtie2 parameters which are working for your specific samples, you can provide them in the configuration parameter: "aln_ref_flags."
( Default values are shown here:  https://cnr-flow.readthedocs.io/en/latest/source/workflow.html#aln-ref )

Also, be sure to look over the Henikoff lab protocols both for CUT&RUN and subsequent data analysis, as these are the primary source for the steps in the pipeline! 
https://www.protocols.io/view/cut-amp-run-targeted-in-situ-genome-wide-profiling-zcpf2vn
https://dx.doi.org/10.17504/protocols.io.bjk2kkye

In addition, feel free to ask any further questions here!

**Comment by EllieDuan** [comment]
Hi, Daniel, 

This is super helpful!! Thank you so much for the detailed information! 

Best,
Ellie
