### ISSUE TITLE
example file a misplaced comma

### ISSUE THREAD

**Issue by EllieDuan** [RenneLab/CnR-flow#3]
Just like to point out a misplaced comma in example file to use fastq_groups:

`Example:`
 `   // fastq_groups = [`
  `  //   'group_1_name': ['treat': 'relpath/to/treat1*R{1,2}*',`
  `  //                    'ctrl':  'relpath/to/ctrl1*R{1,2}*',`
  `  //                   ]`
 `   //   'group_2_name': ['treat': ['relpath/to/g2_treat1*R{1,2}*'`
`    //                              '/abs/path/to/g2_treat2*R{1,2}*'`
 `   //                             ],`
`    //                    'ctrl':  'relpath/to/g2_ctrl1*R{1,2}*'`
`    //                   ]`
`    // ]`

It runs well for multiple groups after moving the comma to the outside of "]"

`Example:`
 `   // fastq_groups = [`
  `  //   'group_1_name': ['treat': 'relpath/to/treat1*R{1,2}*',`
  `  //                    'ctrl':  'relpath/to/ctrl1*R{1,2}*'`
  `  //                   ],`
 `   //   'group_2_name': ['treat': ['relpath/to/g2_treat1*R{1,2}*'`
`    //                              '/abs/path/to/g2_treat2*R{1,2}*'`
 `   //                             ],`
`    //                    'ctrl':  'relpath/to/g2_ctrl1*R{1,2}*'`
`    //                   ]`
`    // ]`
Thanks!

**Comment by dstrib** [comment]
Thanks for pointing this out! Indeed it looks like I even missed another comma.
